### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-191-savkunov#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
7) Відомо, що з серпня 2021 року GitHub-сервер пропонує PAT 
для процесу клонування Private GitHub-репозиторіїв. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by InLoveWithHer** [comment]
GitHub впровадив механізм персональних токенів доступу (PAT) для клонування приватних репозиторіїв з серпня 2021 року з метою підвищення рівня безпеки та контролю над доступом до конфіденційної інформації. Використання PAT забезпечує можливість виділення окремого токена лише для клонування репозиторію, що дозволяє мінімізувати ризики при передачі інформації та обмежити доступ лише до необхідних дій. Такий підхід сприяє підвищенню безпеки розробки та зберігання конфіденційних даних на GitHub.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
