### ISSUE TITLE
Laboratory Work #2

### ISSUE THREAD

**Issue by InLoveWithHer** [oleksandrblazhko/ai-191-savkunov#5]

**Comment by InLoveWithHer** [comment]
Використовувалась методологія STRIDE для аналізу загроз. STRIDE — це абревіатура, що складається з перших літер слів:
- S (Spoofing): Несанкціонований доступ
- T (Tampering): Зміна даних
- R (Repudiation): Заперечення подій
- I (Information Disclosure): Розголошення конфіденційної інформації
- D (Denial of Service): Відмова у обслуговуванні
- E (Elevation of Privilege): Підняття привілеїв

Таким чином, абревіатури STRIDE розшифровуються наступним чином:
- S (Spoofing): Імітація або несанкціонований доступ під час взаємодії з системою.
- T (Tampering): Недозволена зміна, модифікація або втручання у дані.
- R (Repudiation): Здатність користувача заперечити свої дії або події, які відбулися в системі.
- I (Information Disclosure): Несанкціоноване розголошення або витік конфіденційної інформації.
- D (Denial of Service): Спроби перешкодити нормальній роботі системи або наданню послуг користувачам.
- E (Elevation of Privilege): Намагання отримати додаткові привілеї або повноваження в системі.

**Comment by oleksandrblazhko** [comment]
2 бали
